Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### DB vm  ####
  config.vm.define "db1" do |db1|
    db1.vm.box = "geerlingguy/centos7"
    db1.vm.hostname = "db1"
    db1.vm.network "private_network", ip: "192.168.56.15"
    db1.vm.provision "shell", path: "mysql.sh"  

  end
  
### Memcache vm  #### 
  config.vm.define "mc1" do |mc1|
    mc1.vm.box = "geerlingguy/centos7"
    mc1.vm.hostname = "mc1"
    mc1.vm.network "private_network", ip: "192.168.56.14"
    mc1.vm.provision "shell", path: "memcache.sh"  
  end
  
### RabbitMQ vm  ####
  config.vm.define "rmq1" do |rmq1|
    rmq1.vm.box = "geerlingguy/centos7"
  rmq1.vm.hostname = "rmq1"
    rmq1.vm.network "private_network", ip: "192.168.56.16"
    rmq1.vm.provision "shell", path: "rabbitmq.sh"  
  end
  
### tomcat vm ###
   config.vm.define "app1" do |app1|
    app1.vm.box = "geerlingguy/centos7"
    app1.vm.hostname = "app1"
    app1.vm.network "private_network", ip: "192.168.56.12"
    app1.vm.provision "shell", path: "tomcat.sh"  
    app1.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
   end
   
  
### Nginx VM ###
  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/xenial64"
    web1.vm.hostname = "web1"
  web1.vm.network "private_network", ip: "192.168.56.11"
  web1.vm.provision "shell", path: "nginx.sh"  
end
  
end
